name: .NET Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "rel-*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
#    - name: Restore dependencies
#      run: dotnet restore test/UraniumUI.Tests.sln
#    - name: maui-workload
#      run: dotnet workload install maui
#    - name: Restore Workload
#      run: dotnet workload restore test/UraniumUI.Tests.sln --framework net6.0

    - name: Build Source
      run: dotnet build src/UraniumUI/UraniumUI.csproj --framework net6.0
    - name: Build Material
      run: dotnet build src/UraniumUI.Material/UraniumUI.Material.csproj --framework net6.0
    - name: Build
      run: dotnet build test/UraniumUI.Material.Tests/UraniumUI.Material.Tests.csproj --framework net6.0
    - name: Test
      run: dotnet test test/UraniumUI.Material.Tests/UraniumUI.Material.Tests.csproj --framework net6.0
